 const storeData = [
        {
            title: "استخر روباز اکباتان",
            url:"",
            location:"شهرک اکباتان",
            rating:"4.6",
            discount:"20",
            buyCount:"869",
            images:[],
        },
        {
            title: "مجموعه تفریحی ورزشی هودین و هورام",
            url:"",
            location:"تهرانسر ",
            rating:"3.4",
            discount:"16",
            buyCount:"2820",
            images:[],
        },
        {
            title: "استخر روباز هتل اوین ",
            url:"",
            location:"اوین ",
            rating:"4.4",
            discount:"50",
            buyCount:"397",
            images:[],
        },
        {
            title: "استخر روباز هتل اوین ",
            url:"",
            location:"اوین ",
            rating:"4.4",
            discount:"50",
            buyCount:"397",
            images:[],
        },
        {
            title: "استخر روباز هتل اوین ",
            url:"",
            location:"اوین ",
            rating:"4.4",
            discount:"50",
            buyCount:"397",
            images:[],
        },
        {
            title: "استخر روباز هتل اوین ",
            url:"",
            location:"اوین ",
            rating:"4.4",
            discount:"50",
            buyCount:"397",
            images:[],
        },
        {
            title: "استخر روباز هتل اوین ",
            url:"",
            location:"اوین ",
            rating:"4.4",
            discount:"50",
            buyCount:"397",
            images:[],
        },
        {
            title: "استخر روباز هتل اوین ",
            url:"",
            location:"اوین ",
            rating:"4.4",
            discount:"50",
            buyCount:"397",
            images:[],
        },
        {
            title: "استخر روباز هتل اوین ",
            url:"",
            location:"اوین ",
            rating:"4.4",
            discount:"50",
            buyCount:"397",
            images:[],
        },
        {
            title: "استخر روباز هتل اوین ",
            url:"",
            location:"اوین ",
            rating:"4.4",
            discount:"50",
            buyCount:"397",
            images:[],
        },
 
]


export const getData = () => {
    return storeData;
   }