// "use client";
import "./globals.css";
// import { Inter } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";

import Footer from "@/components/footer";
import Header from "@/components/header";
import MainSidebar from "@/components/sidebarMobileRTL/MainSidebar";
import MainSearch from "@/components/mainsearchmobile/MainSearch";
// import { usePathname } from 'next/navigation';

import { Providers } from "@/redux/Provider";
// import { LayoutProvider } from "../LayoutProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return [{ locale: "fa" }, { locale: "ar" }, { locale: "en" }];
}

export default async function RootLayout({ children, params: { locale } }) {
  // const pathname = usePathname();
  let messages;
  try {
    messages = (await import(`../../messages/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }
  return (
    <html
      lang={locale}
      dir={locale == "fa" ? "rtl" : locale == "ar" ? "rtl" : "ltr"}
      data-theme="light"
    >
      <Providers>
        <body dir={locale == "fa" ? "rtl" : locale == "ar" ? "rtl" : "ltr"}>
          <NextIntlClientProvider locale={locale} messages={messages}>
            {/* <LayoutProvider> */}
            <Header />
            {children}
            <MainSidebar />
            <MainSearch />
            <Footer />

            {/* </LayoutProvider> */}
          </NextIntlClientProvider>
        </body>
      </Providers>
    </html>
  );
}
